### ISSUE TITLE
Git Action Token 인식 못하는 문제

### ISSUE THREAD

**Issue by ambosing** [Woowa-Birdies/MealBuddy_Backend#12]
dev-CD Git Action yaml 파일에 Checkout 부분에 토큰 인식을 못하는 버그 발생

Input required and not supplied: token

```
# workflow의 이름
name: DEV-CD

on:
  pull_request:
    types: [ closed ]
    branches: [ "dev" ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: Dev-CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.ACTION_SECRETS }} # <- 여기
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Copy secret files
        run: ./gradlew copySecret
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Deliver File
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "build/libs/*.jar"
          target: "~/app"
          rm: true

      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            SOURCE_DIR=~/app/build/libs
            FILE_NAME=`find $SOURCE_DIR/*.jar -printf "%f\n"`
            PID=`$(ps -ef | grep "java -jar" | grep "$FILE_NAME" | awk '{print $2}')`

            if [ -z "$PID" ]; then
                    echo "#### THERE IS NO PROCESS ####"
            else
                    echo "#### KILL $PID ####"
                    sudo kill $PID
            fi

            echo "#### RUN $SOURCE_DIR/$FILE_NAME ####"
            sudo nohup java -jar $SOURCE_DIR/$FILE_NAME > application.log 2>&1 &
```

시도한 부분 
- Secrets에서 있는 변수명 확인해보고 다시 수정
- Secrets에 있는 ACTION_SECRETS 값도 재발급해서 수정해보고 재시도

이 문제 아시는 분 댓글 달아주시면 감사하겠습니다
